base_model: /jfan5/sft_models/mistral_7b/symbolized_v2
batch_size: 4
beta: 0.05
class_label_field: class_label
dataloader_num_workers: 0
dataset: /jfan5/grpo_data/five_domain_0109/blocksworld.jsonl
gradient_accumulation_steps: 4
learning_rate: 5.0e-06
logging_steps: 50
max_grad_norm: 1.0
max_new_tokens: 512
max_prompt_length: 2048
max_steps: 1000
no_4bit: false
no_run_tracking: false
no_wandb: false
num_epochs: 1.0
num_generations: 4
output_dir: /jfan5/grpo_models/mistral_7b-symbolized-0109-stl-1000
prompt_field: prompt
response_field: response
run_name: grpo_mistral_7b-symbolized-0109-stl
runs_root: ./runs
save_steps: 100
seed: 3407
temperature: 0.6
top_k: 50
top_p: 0.9
use_gradient_checkpointing: false
wandb_project: pddl-grpo-mistral7b
