base_model: /jfan5/sft_models/llama31_8b/symbolized
batch_size: 4
beta: 0.05
class_label_field: class_label
dataloader_num_workers: 0
dataset: /jfan5/grpo_data/five_domain_0108/combined.jsonl
gradient_accumulation_steps: 4
learning_rate: 5.0e-06
logging_steps: 20
max_grad_norm: 1.0
max_new_tokens: 512
max_prompt_length: 2048
max_steps: 1000
no_4bit: false
no_run_tracking: false
no_wandb: false
num_epochs: 1.0
num_generations: 4
output_dir: /jfan5/grpo_models/llama31_8b-stl-20260108_22
prompt_field: prompt
response_field: response
run_name: grpo_llama3.1-8b-stl-20260108_22
runs_root: ./runs
save_steps: 60
seed: 3407
temperature: 0.6
top_k: 50
top_p: 0.9
use_gradient_checkpointing: false
wandb_project: pddl-grpo-llama31-8b
