batch_size: 8
eval_id: solver_batch__temp0.6_max512_bs8
eval_type: solver_batch
load_in_4bit: true
max_new_tokens: 512
max_problems: 50
model_path: /jfan5/grpo_models/qwen3_14b-symbolized-1221-stl-1000
num_workers: 8
one_shot: false
temperature: 0.6
timestamp: '2026-01-07T15:30:20.563458'
