eval_id: solver__temp0.6_max1024
eval_type: solver
load_in_4bit: true
max_new_tokens: 1024
max_problems: 3
model_path: /jfan5/grpo_models/mistral_7b-blocksworld-stl-121-2
one_shot: false
temperature: 0.6
timestamp: '2026-01-05T22:29:27.385695'
