batch_size: 8
eval_id: solver_batch__temp0.6_max512_bs8
eval_type: solver_batch
load_in_4bit: true
max_new_tokens: 512
max_problems: 100
model_path: /jfan5/grpo_models/llama31_8b-stl-blocksworld-20260108_20/checkpoint-360
num_workers: 8
one_shot: false
temperature: 0.6
timestamp: '2026-01-09T03:28:32.851909'
