batch_size: 8
eval_id: solver_batch__temp0.6_max512_bs8_20260124_203548
eval_type: solver_batch
load_in_4bit: true
max_new_tokens: 512
max_problems: 50
model_path: /jfan5/grpo_models/grpo_mistral_7b-curriculum_v2-all-0112-stl
num_workers: 8
one_shot: false
temperature: 0.6
timestamp: '2026-01-24T20:48:13.412943'
