dataset: /jfan5/sft_data/four_scenarios_simple/combined.hf
disable_wandb: false
eval_steps: null
eval_strategy: epoch
family: qwen
gradient_accumulation_steps: 2
learning_rate: 0.0002
list_scenarios: false
load_in_4bit: true
logging_steps: 10
lora_alpha: 64
lora_dropout: 0.05
lora_r: 32
lora_target_modules: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
lr_scheduler_type: null
max_grad_norm: null
max_seq_length: 4096
mode: train
model: unsloth/Qwen3-14B-unsloth-bnb-4bit
no_run_tracking: false
num_train_epochs: 3.0
output: /jfan5/sft_models/qwen3_14b/four_scenarios500_0126
per_device_train_batch_size: 4
reasoning: null
run_name: null
runs_root: ./runs
save_steps: null
save_strategy: epoch
save_total_limit: 3
seed: 3407
test_count: 3
test_prompt: Generate a PDDL solution for a simple problem.
val_ratio: 0.05
wandb_entity: null
wandb_project: pddl-finetune
warmup_ratio: null
weight_decay: null
