batch_size: 2
eval_id: solver_batch__temp0.6_max512_bs2_20260125_181016
eval_type: solver_batch
load_in_4bit: true
max_new_tokens: 512
max_problems: 5
model_path: /jfan5/grpo_models/qwen3-14b-curriculum_v2-all-0111-stl-1000
num_workers: 4
one_shot: false
temperature: 0.6
timestamp: '2026-01-25T18:10:16.607919'
