batch_size: 8
eval_id: solver_batch__temp0.6_max512_bs8_20260202_040446
eval_type: solver_batch
load_in_4bit: true
max_new_tokens: 512
max_problems: 50
model_path: runs/mistral/sft/default_run_20260201_184350_seed3407/model
num_workers: 8
one_shot: false
temperature: 0.6
timestamp: '2026-02-02T04:12:03.949615'
