domain: blocksworld
domain_file: /home/ubuntu/Safety-gen/pddl3/blocksworld/domain3.pddl
family: qwen
load_in_4bit: true
max_new_tokens: 512
max_problems: 0
max_retries: 5
model_path: /jfan5/grpo_models/qwen3-14b-curriculum_v2-all-0111-stl-1000
problems_dir: /home/ubuntu/Safety-gen/pddl3/blocksworld/testing_problem50
temperature: 0.6
