base_model: /jfan5/sft_models/mistral_7b/cross_domain_pddl3_symbolized
batch_size: 4
beta: 0.02
data_root: /jfan5/grpo_data/five_domain_0109
domains: blocksworld
gradient_accumulation_steps: 1
learning_rate: 1.0e-05
logging_steps: 10
max_grad_norm: 1.0
max_new_tokens: 512
max_prompt_length: 2048
max_steps: 100
no_4bit: false
no_run_tracking: false
no_wandb: false
num_generations: 4
output_dir: /jfan5/grpo_models/mistral_7b_v2_blocksworld_20260110_020034
run_name: grpo-v2-mistral7b-blocksworld
runs_root: ./runs
save_steps: 50
seed: 3407
temperature: 0.8
top_k: 50
top_p: 0.9
use_gradient_checkpointing: true
wandb_project: pddl-grpo-training-v2
