eval_id: solver__temp0.6_max1024_20260123_163721
eval_type: solver
load_in_4bit: true
max_new_tokens: 1024
max_problems: 50
model_path: /jfan5/grpo_models/qwen3-14b-curriculum_v2-all-0111-stl-1000
one_shot: false
temperature: 0.6
timestamp: '2026-01-23T16:37:21.656709'
